### ISSUE TITLE
Stances = Broken

### ISSUE THREAD

**Issue by JaysProjex** [stoneharry/Spell-Editor-GUI-V2#11]
Great editor but some more tuning is required.

Practically everything in the stances tab starting after "Ambient" will not stay checked.

Spell Editor ---> Flags ---> Misc ---> Stances ---> Ghoul (down to) Spirit of Redemption (do not work as intended)

Once saved they uncheck & randomly select other options (typically on ambient or above it)

~I just noticed you fixed it a day ago~ 

~Re-opened~

Stances are still not fixed

**Comment by stoneharry** [comment]
Did you compile yourself or are you using the latest release? The latest release does not contain the bug fix.

**Comment by stoneharry** [comment]
If you cannot test the latest version because you cannot compile it yourself then I will be pushing a new build within the next few days. I am currently actively developing a new branch: 

https://github.com/stoneharry/Spell-Editor-GUI-V2/commits/MySQL

**Comment by stoneharry** [comment]
A new build has been released. Test to see if the bug exists in the new version.

**Comment by JaysProjex** [comment]
How disappointing, I dislike the new process of SQL importing. I'll stick with the previous buggy version & use dbc editor thanks anyways.

**Comment by stoneharry** [comment]
This is an immature comment and not relevant to the discussion. If you cannot work this then you don't deserve to run a server. This tool now integrates directly into project workflow allowing for precise logging of exactly what records have been changed and how, allows cross-network editing on the same file, provides better security and version control. Along with a host of other benefits.

**Comment by JaysProjex** [comment]
How you handle feedback with that type attitude is poor & immature, I reported a bug as you suggested. Then odd days later a entire new build is released when I just got done getting use to the previous version & then you changed how it works entirely. Yea you're right I don't deserve to work like this because I'm actually "different" than most. Really harry I thought you could take criticism better than this, not everyone is going to adapt to change like you can but good riddance.

**Comment by stoneharry** [comment]
This is not useful feedback. This is you just moaning because you don't like improvements that you don't understand. This is the attitude I get from people on Ac-Web - I am not here to cater to amateur developers who cannot deal with normal computing technologies. This is pretty basic stuff.

I don't expect a random person to understand how to set up this tool and why this is infinitely better than previous versions. But this is designed for them - this is designed for a server administrator to setup and manage, while distributing the tool with a preconfigured config.xml to developers for their project.

And your comments are simply not on topic for this bug report. The bug was fixed and the issue closed. Stating how you dislike this tool for no justifiable reason and then stating how you will stay on a buggy version is just immature. There is not a lot new to learn - the only thing that has changed is the data storage medium.

"Not everyone is going to adapt to change like you" - I expect any person running a server to easily understand why these changes were implemented and to be able to set it up appropriately. And hopefully take advantage of the new features it allows. If you cannot you should not be running a WoW emulator. If you are doing it for fun and personal experimentation you should understand you are not going to understand everything and not expect help in this venture. It is your responsibility to make sure that you understand the technologies you are getting involved in, and MySQL is core to the TrinityCore and all other WoW emulators development process.

Further off-topic comments will be removed. This issue is closed.
