### ISSUE TITLE
Error trying to use another user than root

### ISSUE THREAD

**Issue by Dokman** [stoneharry/Spell-Editor-GUI-V2#13]
![image](https://cloud.githubusercontent.com/assets/2290904/9140374/04789278-3d31-11e5-93d7-9109236e7953.png)

**Comment by stoneharry** [comment]
Try using localhost rather than 127.0.0.1. You can change this in the config.XML.

**Comment by Dokman** [comment]
i do it, i changed in the config.cs and works but i have this error now
![image](https://cloud.githubusercontent.com/assets/2290904/9140678/3a28853e-3d33-11e5-9bde-b72e4f9ff95a.png)

**Comment by stoneharry** [comment]
Interesting error. I can take a look at it in a few hours.

**Comment by Dokman** [comment]
this should be perfect :sunrise:

**Comment by stoneharry** [comment]
Confirmed it's a bug with the MySQL server software: http://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql

Fixed in: 22e0b52466c0d0d1cc1605772b4cd4a548ccffff

Check the latest release for a hopefully fixed version. I updated the existing release actually: https://github.com/stoneharry/Spell-Editor-GUI-V2/releases/tag/v1.4

**Comment by Dokman** [comment]
so for now how i use it remotely changing only the xml? is for one partner use it

**Comment by stoneharry** [comment]
Huh? You connect to a remote MySQL server the same way you do with Navicat/SQLyog etc. You need to have a MySQL server that has the port for it open and create a user that can connect from external IP's.

I cannot give guides on this. This is a tool, not a MySQL tutorial. :)

Seems the bug is fixed anyway so I am going to close this report.

**Comment by Dokman** [comment]
i am saying when i forwarded the ports and i have all done, to connect another person i only have to create a user and setup his config no?

**Comment by stoneharry** [comment]
Yes.
