### ISSUE TITLE
 does not support Chinese.

### ISSUE THREAD

**Issue by bubbleatgit** [stoneharry/Spell-Editor-GUI-V2#17]
does not support Chinese.

**Comment by stoneharry** [comment]
Can you give a better description please? What part doesn't support Chinese? When does it happen and is there an error? Screenshots?

**Comment by bubbleatgit** [comment]
thank you for your answer.
when i import dbc files to mysql, 'spellName4'  spell's description can not display chinese.
![qq 20150906215741](https://cloud.githubusercontent.com/assets/7858776/9704700/683b94ea-54e2-11e5-9909-65a3aaf1a4a0.png)
![qq 20150906215811](https://cloud.githubusercontent.com/assets/7858776/9704701/691048b6-54e2-11e5-81d0-d0b664e194c4.png)

**Comment by stoneharry** [comment]
This change might fix it but I don't have time to test it right now or deploy a new release build:

https://github.com/stoneharry/Spell-Editor-GUI-V2/commit/a25ba612c921ff571a7ab8af753d643267b84835

If you want to test it you will need to compile it yourself and recreate the MySQL table after using the updated version (change table name or drop the existing table).

The issue is that the MySQL table is not storing it using the UTF8 charset currently.

**Comment by bubbleatgit** [comment]
Thanks , i will test
