### ISSUE TITLE
MySQL save error

### ISSUE THREAD

**Issue by Athris** [stoneharry/Spell-Editor-GUI-V2#23]
So i use your newest program version, but the save function does not work on some spells.

For example: 9472

Error message: Concurrency violation: the UpdateCommand affected 0 of the expected 1 records

**Comment by stoneharry** [comment]
This is because it's trying to update by finding spells based on every column, e.g:

`UPDATE `spelleditor`.`spell` SET `Stances` = 0, `EffectMultipleValue2` = 1, `EffectMultipleValue3` = 1, `SpellToolTipFlags7` = 16712190 WHERE ((`ID` = 9472) AND (`Category` = 0) AND (`Dispel` = 0) AND (`Mechanic` = 0) AND (`Attributes` = 65536) AND (`AttributesEx` = 0) AND (`AttributesEx2` = 524288) AND (`AttributesEx3` = 0) AND (`AttributesEx4` = 0) AND (`AttributesEx5` = 0) AND (`AttributesEx6` = 0) AND (`AttributesEx7` = 0) AND (`Stances` = 2147483648) AND (`Unknown1` = 0) AND (`StancesNot` = 134217728) AND (`Unknown2` = 0) AND (`Targets` = 0) AND (`TargetCreatureType` = 0) AND (`RequiresSpellFocus` = 0) AND (`FacingCasterFlags` = 0) AND (`CasterAuraState` = 0) AND (`TargetAuraState` = 0) AND (`CasterAuraStateNot` = 0) AND (`TargetAuraStateNot` = 0) AND (`CasterAuraSpell` = 0) AND (`TargetAuraSpell` = 0) AND (`ExcludeCasterAuraSpell` = 0) AND (`ExcludeTargetAuraSpell` = 0) AND (`CastingTimeIndex` = 16) AND (`RecoveryTime` = 0) AND (`CategoryRecoveryTime` = 0) AND (`InterruptFlags` = 15) AND (`AuraInterruptFlags` = 0) AND (`ChannelInterruptFlags` = 0) AND (`ProcFlags` = 0) AND (`ProcChance` = 101) AND (`ProcCharges` = 0) AND (`MaximumLevel` = 31) AND (`BaseLevel` = 26) AND (`SpellLevel` = 26) AND (`DurationIndex` = 0) AND (`PowerType` = 0) AND (`ManaCost` = 0) AND (`ManaCostPerLevel` = 0) AND (`ManaPerSecond` = 0) AND (`ManaPerSecondPerLevel` = 0) AND (`RangeIndex` = 5) AND (`Speed` = 0) AND (`ModalNextSpell` = 0) AND (`StackAmount` = 0) AND (`Totem1` = 0) AND (`Totem2` = 0) AND (`Reagent1` = 0) AND (`Reagent2` = 0) AND (`Reagent3` = 0) AND (`Reagent4` = 0) AND (`Reagent5` = 0) AND (`Reagent6` = 0) AND (`Reagent7` = 0) AND (`Reagent8` = 0) AND (`ReagentCount1` = 0) AND (`ReagentCount2` = 0) AND (`ReagentCount3` = 0) AND (`ReagentCount4` = 0) AND (`ReagentCount5` = 0) AND (`ReagentCount6` = 0) AND (`ReagentCount7` = 0) AND (`ReagentCount8` = 0) AND (`EquippedItemClass` = -1) AND (`EquippedItemSubClassMask` = 0) AND (`EquippedItemInventoryTypeMask` = 0) AND (`Effect1` = 10) AND (`Effect2` = 0) AND (`Effect3` = 0) AND (`EffectDieSides1` = 57) AND (`EffectDieSides2` = 0) AND (`EffectDieSides3` = 0) AND (`EffectRealPointsPerLevel1` = 2.2) AND (`EffectRealPointsPerLevel2` = 0) AND (`EffectRealPointsPerLevel3` = 0) AND (`EffectBasePoints1` = 257) AND (`EffectBasePoints2` = 0) AND (`EffectBasePoints3` = 0) AND (`EffectMechanic1` = 0) AND (`EffectMechanic2` = 0) AND (`EffectMechanic3` = 0) AND (`EffectImplicitTargetA1` = 21) AND (`EffectImplicitTargetA2` = 0) AND (`EffectImplicitTargetA3` = 0) AND (`EffectImplicitTargetB1` = 0) AND (`EffectImplicitTargetB2` = 0) AND (`EffectImplicitTargetB3` = 0) AND (`EffectRadiusIndex1` = 0) AND (`EffectRadiusIndex2` = 0) AND (`EffectRadiusIndex3` = 0) AND (`EffectApplyAuraName1` = 0) AND (`EffectApplyAuraName2` = 0) AND (`EffectApplyAuraName3` = 0) AND (`EffectAmplitude1` = 0) AND (`EffectAmplitude2` = 0) AND (`EffectAmplitude3` = 0) AND (`EffectMultipleValue1` = 1) AND (`EffectMultipleValue2` = 0) AND (`EffectMultipleValue3` = 0) AND (`EffectChainTarget1` = 0) AND (`EffectChainTarget2` = 0) AND (`EffectChainTarget3` = 0) AND (`EffectItemType1` = 0) AND (`EffectItemType2` = 0) AND (`EffectItemType3` = 0) AND (`EffectMiscValue1` = 0) AND (`EffectMiscValue2` = 0) AND (`EffectMiscValue3` = 0) AND (`EffectMiscValueB1` = 0) AND (`EffectMiscValueB2` = 0) AND (`EffectMiscValueB3` = 0) AND (`EffectTriggerSpell1` = 0) AND (`EffectTriggerSpell2` = 0) AND (`EffectTriggerSpell3` = 0) AND (`EffectPointsPerComboPoint1` = 0) AND (`EffectPointsPerComboPoint2` = 0) AND (`EffectPointsPerComboPoint3` = 0) AND (`EffectSpellClassMaskA1` = 0) AND (`EffectSpellClassMaskA2` = 0) AND (`EffectSpellClassMaskA3` = 0) AND (`EffectSpellClassMaskB1` = 0) AND (`EffectSpellClassMaskB2` = 0) AND (`EffectSpellClassMaskB3` = 0) AND (`EffectSpellClassMaskC1` = 0) AND (`EffectSpellClassMaskC2` = 0) AND (`EffectSpellClassMaskC3` = 0) AND (`SpellVisual1` = 3077) AND (`SpellVisual2` = 0) AND (`SpellIconID` = 242) AND (`ActiveIconID` = 0) AND (`SpellPriority` = 50) AND (`SpellNameFlag0` = 0) AND (`SpellNameFlag1` = 0) AND (`SpellNameFlag2` = 0) AND (`SpellNameFlag3` = 0) AND (`SpellNameFlag4` = 0) AND (`SpellNameFlag5` = 0) AND (`SpellNameFlag6` = 0) AND (`SpellNameFlag7` = 16712190) AND (`SpellRankFlags0` = 0) AND (`SpellRankFlags1` = 0) AND (`SpellRankFlags2` = 0) AND (`SpellRankFlags3` = 0) AND (`SpellRankFlags4` = 0) AND (`SpellRankFlags5` = 0) AND (`SpellRankFlags6` = 0) AND (`SpellRankFlags7` = 16712190) AND (`SpellDescriptionFlags0` = 0) AND (`SpellDescriptionFlags1` = 0) AND (`SpellDescriptionFlags2` = 0) AND (`SpellDescriptionFlags3` = 0) AND (`SpellDescriptionFlags4` = 0) AND (`SpellDescriptionFlags5` = 0) AND (`SpellDescriptionFlags6` = 0) AND (`SpellDescriptionFlags7` = 16712190) AND (`SpellToolTipFlags0` = 0) AND (`SpellToolTipFlags1` = 0) AND (`SpellToolTipFlags2` = 0) AND (`SpellToolTipFlags3` = 0) AND (`SpellToolTipFlags4` = 0) AND (`SpellToolTipFlags5` = 0) AND (`SpellToolTipFlags6` = 0) AND (`SpellToolTipFlags7` = 16712188) AND (`ManaCostPercentage` = 18) AND (`StartRecoveryCategory` = 133) AND (`StartRecoveryTime` = 1500) AND (`MaximumTargetLevel` = 0) AND (`SpellFamilyName` = 6) AND (`SpellFamilyFlags` = 2048) AND (`SpellFamilyFlags1` = 0) AND (`SpellFamilyFlags2` = 0) AND (`MaximumAffectedTargets` = 0) AND (`DamageClass` = 1) AND (`PreventionType` = 1) AND (`StanceBarOrder` = 0) AND (`EffectDamageMultiplier1` = 1) AND (`EffectDamageMultiplier2` = 1) AND (`EffectDamageMultiplier3` = 1) AND (`MinimumFactionId` = 0) AND (`MinimumReputation` = 0) AND (`RequiredAuraVision` = 0) AND (`TotemCategory1` = 0) AND (`TotemCategory2` = 0) AND (`AreaGroupID` = 0) AND (`SchoolMask` = 2) AND (`RuneCostID` = 0) AND (`SpellMissileID` = 0) AND (`PowerDisplayId` = 0) AND (`EffectBonusMultiplier1` = 0.807) AND (`EffectBonusMultiplier2` = 0) AND (`EffectBonusMultiplier3` = 0) AND (`SpellDescriptionVariableID` = 0) AND (`SpellDifficultyID` = 0))`

The fix for this is trying to tell it to match on the primary key only, e.g:

`        public void commitChanges(String query, DataTable dataTable)
        {
            if (_updating)
                return;
            lock (syncLock)
            {
                var adapter = new MySqlDataAdapter();
                var mcb = new MySqlCommandBuilder(adapter);
                adapter.SelectCommand = new MySqlCommand(query, conn);

                DataColumn[] id = new DataColumn[1];
                id[0] = dataTable.Columns["ID"];
                dataTable.PrimaryKey = id;

                adapter.Update(dataTable);
                dataTable.AcceptChanges();
            }
        }`

But I haven't got this to work from some quick testing yet. I will work on it again tomorrow hopefully.

**Comment by Athris** [comment]
I try your fix, but it dont work.

**Comment by stoneharry** [comment]
I fixed it!

`UPDATE `spelleditor`.`spell` SET `Stances` = 0, `EffectMultipleValue2` = 1, `EffectMultipleValue3` = 1, `SpellName0` = 'Flash Heal Test', `SpellToolTipFlags7` = 16712190 WHERE ((`ID` = 9472))`

The updated function:

`        public void commitChanges(String query, DataTable dataTable)
        {
            if (_updating)
                return;
            lock (syncLock)
            {
                var adapter = new MySqlDataAdapter();
                var mcb = new MySqlCommandBuilder(adapter);
                mcb.ConflictOption = ConflictOption.OverwriteChanges;
                adapter.SelectCommand = new MySqlCommand(query, conn);
                adapter.Update(dataTable);
                dataTable.AcceptChanges();
            }
        }`

The `ConflictOption.OverwriteChanges` fixes this issue by only checking the primary key. I will push a new version shortly.

**Comment by stoneharry** [comment]
Fixed with https://github.com/stoneharry/Spell-Editor-GUI-V2/commit/3219d381d18d5b9d6aeaf7bc0d358ae6a89b2ebb.

**Comment by Athris** [comment]
Thank you! :)
