### ISSUE TITLE
Editor thinks Duration Index ID 21 is too large/small for an Int32 [bug]

### ISSUE THREAD

**Issue by RikuAotsuki** [stoneharry/Spell-Editor-GUI-V2#56]
This may actually be related to the issue someone opened 3 days ago.

If I change the duration index to ID 21, save, close the editor, and then come back to it later, the "Value was too large or too small for an Int32" error tends to appear. I'm not FULLY certain what triggers it in this case, but it might actually be the tooltip tag trying to call the value, because I just tested it on spell 696-Demon Skin (Rank 2). I had to actually edit the duration index in the dbc itself for the editor to allow me to edit the spell, and all I did was remove the duration part of the tooltip and set the duration index to ID 21 again. Saved, closed, reopened, and it allowed me to select the spell. So I'm not certain if it's just the tag, or some kind of variable I'm not aware of, but it's DEFINITELY related to the duration.

**Comment by Makpptfox** [comment]
Just removing the $d in the spell description is a workaround, but the issue comes even without modifying anything on some clean spells, like the spell ID 59414 which is using the durationindex 21 and the tag $d in the description by default but can't be opened in the editor.

I changed the int into bigint into the MySQL table to see if it was that easy - of course it wasn't.

For me it may be related to the "real time updating description" (aka the description that interprets the tags on the right of the one we can write in, if I'm not clear enough)

Hope it helps you to find the issue.

**Comment by stoneharry** [comment]
I have reproduced this with spell ID 59414. I will work on getting it fixed as soon as possible. Thanks for the report! 👍 

![Error using spell Id 59414](https://i.imgur.com/Ns2N6sb.png)

**Comment by stoneharry** [comment]
Fixed in: f01d77377452c841a7490dbcd9b165fbd401a03e

I will release a new version soon.

![Spell Id 59414 loaded successfully](https://i.imgur.com/DQuPGNc.png)

**Comment by stoneharry** [comment]
Release build v1.8.0 should fix this issue. Closing - thanks for the report.
